### ISSUE TITLE
Task Need for assigning the adapterid to another user (and/or device)

### ISSUE THREAD

**Issue by HHeermann** [vicinityh2020/issue-tracking#10]
Sometimes there is a need to assign the adapter id to another user. We tried this and we get the following error

java.lang.Exception: duplicate adapter-id [009c93940b] in agent [d56a516e-caae-467f-9a97-eab073a41dd7] .. adapter id is already used in another agent [e2abe379-9334-4624-9ade-74ad0c44395d]!at sk.intersoft.vicinity.agent.service.config.AgentConfig.create(AgentConfig.java:344)

So there is a need to remove from the old user the adapterid configuration with some way (the question is who is responsible for that)After that agent is now working for both cases and needs some manual configurationDo you have something to propose for this case?

cc: user#9

**Comment by MooXo** [comment]
Resolved in the version v0.6.3.3 v Neighbourhood Manager.
