### ISSUE TITLE
Feature Req. Agent and Gateway Deployment in a kind of Private Network

### ISSUE THREAD

**Issue by HHeermann** [vicinityh2020/issue-tracking#11]
We finished installation of vicinity modules in municipality but we face a problem with gateway and agent. We moved the components fropm our test environment to production and saw that the agent can’t populate the existing configs. After searching a bit, we found that gateway doesn’t start correctly and this is probably from its config

server: vicinity.bavenir.eu
port: 5222

As I understand the gateway tries to communicate with the above server, something that is not allowed in municipality environment due to government firewalls (don’t allow outgoing to such ports). Could it be possible to change the config and proxy your server to an allowed port (80,443)

**Comment by MooXo** [comment]
Dear HHeermann,

you are correct VICINITY Gateway API is communicating with Communication Server using XMPP protocol. In future version it is planned the XMPP over HTTP.

Thank you for your suggestions.

Best regards.

Viktor
