### ISSUE TITLE
Bug Semantic repository endpoint 'annotations/hierarchy' returns duplicates

### ISSUE THREAD

**Issue by HHeermann** [vicinityh2020/issue-tracking#12]
The semantic repository endpoint which provides hierarchical structure of the Ontology classess includes duplicates:
![SemRepBugImg](https://user-images.githubusercontent.com/57433080/68287932-d60b4500-0083-11ea-9927-3fced03df6e0.png)

**Comment by MooXo** [comment]
The issue was resolved in version of 0.7 of semantic repository.
