### ISSUE TITLE
Number of devices in NM after parallel discovery test does not match (related to NM-interface, NM-api and agent)

### ISSUE THREAD

**Issue by HHeermann** [vicinityh2020/issue-tracking#13]
Test case:

- fresh access point with 0 devices in NM

- GTW v0.6.3.1 started locally

- agent v0.6.3.1 with 5 active adapters started locally

- adapters are started in separated threads and issue POST operation with 5 IoT objects/TDs to the agent with status OK as result

- state of the NM after the test is 10 devices instead of 25 expected

Logs of the GTW, agent and console output of the test itself are attached to the issue, as well as the picture with the NM state after the test.

[5x5_OK_logs.zip](https://github.com/vicinityh2020/issue-tracking/files/3813788/5x5_OK_logs.zip)

**Comment by MooXo** [comment]
The issue was resolved in the latest version of the VICINITY Gateway API v0.8, please update your dockers.
