### ISSUE TITLE
Allow dynamic thing descriptions

### ISSUE THREAD

**Issue by JensKolb** [vicinityh2020/issue-tracking#14]
**Is your feature request related to a problem? Please describe.**
The Thing Description does not support dynamic changes

**Describe the solution you'd like**
Either: dynamic changes to the thing description (e.g. by making return_td callable)
Or: allow objects without static prop fields in the thing description 

**Describe alternatives you've considered**
Having a string prop which contains a json string; defies the concept of the thing description

**Comment by MooXo** [comment]
Hi JensKolb,

what would you like to try to achieve with dynamic changes?

Thank you

Viktor
