### ISSUE TITLE
Add user

### ISSUE THREAD

**Issue by MilanJovic92** [vicinityh2020/issue-tracking#2]
Hello,
how can I add a new person from the same organization?
Thank you

**Comment by MooXo** [comment]
Dear MikibeMiki,

I guess you would like to add new user in the same organization, only icon in upper right corner and invite new user in your organization.

<img width="390" alt="Screenshot 2019-06-04 at 10 07 43" src="https://user-images.githubusercontent.com/2355720/58862398-e4a69800-86b0-11e9-998f-4064ba85f8df.png">

Best regards.

Viktor

**Comment by MilanJovic92** [comment]
Thank you
