### ISSUE TITLE
Change service access level from private to public

### ISSUE THREAD

**Issue by pesicsasa** [vicinityh2020/issue-tracking#6]
**Describe the bug**
By default services are exposed as private. Even though the user has all admin roles, when he/she tries to set the service to public, an error is reported indicating that the user is unauthorized or has access level too low. There is no clear procedure on how to get enough permissions in order to make your services publicly available.

**To Reproduce**
1. Expose your service using adapter thing description
2. Go to your organization private services 
3. Select a service and click on more info
4. In the service tab use Access Level select button (by default it's set to private) to change to Public with Data under request option
5. You will receive notification: User is unauthorized or access level to low

**Screenshots**
This image shows the user profile with list of all roles assigned to him.
![picturemessage_ttu241nv yw5](https://user-images.githubusercontent.com/15779703/60594311-f4df8f00-9da4-11e9-83bd-d6d8c3f5aab0.png)

This image shows how the service responds when a user tries to change the service access level to public.
![picturemessage_shzzd4fi w1r](https://user-images.githubusercontent.com/15779703/60594422-36703a00-9da5-11e9-96fd-7e4221084895.png)

**Comment by MooXo** [comment]
The user owning the device or service needs to change visibility of its profile to public before.

This is current workaround.

We are fixing this constrained in next versions.
