### ISSUE TITLE
Infrastructure id

### ISSUE THREAD

**Issue by ghost** [vicinityh2020/issue-tracking#7]
Hi! We have tried publishing events through adapter but we need iid. How can we find iid?

**Comment by AndrejSeben** [comment]
Hi, I dont know, from OGWAPI side you (or adapter in your case) should make PUT request to OGWAPI/events/{eid} ... so OGWAPI doesnt need this iid parameter for fire to the event and send it to subscribers ..... https://vicinityh2020.github.io/vicinity-gateway-api/#/events/putEventsEid

Where exactly do you need to use this parameter? Can you describe a wider context?

**Comment by ghost** [comment]
In example-adapter we downloaded, there is route "/objects/{iid}/publishers/{oid}/events/{eid}" to EventPublisherResource class we tried to test, but struggled to find iid.

**Comment by AndrejSeben** [comment]
So, I have some information from Peter Kostelni who implements this adapter .... iid is the infrastructure id, it is the internal object id on the adapter side and you defined it in the thing description.

**Comment by MooXo** [comment]
From innactivity point of view i am closing this issue.
