### ISSUE TITLE
PUT object attributes and GET new value

### ISSUE THREAD

**Issue by quintanilha6** [vicinityh2020/issue-tracking#9]
Runnig OGWAPI, adapter and agent I can successfully get agent config and object attributes. Although, when I try to PUT a property, I get a success message (as shown below), but I can't read the new value anywhere. Here is the schema of one of my adapters as well as some general info that might be useful to solve this issue. 

OGWAPI port 8181
Adapter port 9998
Agent port 9997

ADAPTER SCHEMA
```
{
  "adapter-id": "EVCharger-adapter",
  "thing-descriptions": [
    {
      "oid": "EVCharger-1",
      "name": "evcharger",
      "type": "adapters:EVCharger",
      "located-in": [
        {
          "location_type": "s4city:City",
          "label": "Portugal",
          "location_id": "http://en.enercoutim.eu/"
        }
      ],
      "properties": [
       
...
        
        {
          "pid": "status",
          "monitors": "adapters:AmbientTemperature",
          "read_link": {
            "href": "/objects/{oid}/properties/{pid}",
            "output": {
              "type": "object",
              "field": [
                {
                  "name": "status",
                  "schema": {
                    "type": "string"
                  }
                }
              ]
            }
          },
          "write_link": {
            "href": "/objects/{oid}/properties/{pid}",
            "input": {
              "type": "object",
              "field": [
                {
                  "name": "status",
                  "schema": {
                    "type": "string"
                  }
                }
              ]
            },
            "output": {
              "type": "object",
              "field": [
                {
                  "name": "success",
                  "schema": {
                    "type": "boolean"
                  }
                }
              ]
            }
          }
        }
      ],
      "actions": [],
      "events": []
    }
...
```

REQUEST
`GET http://localhost:9997/agent/configuration `

RESPONSE
```
{
    "adapters": [
        {
            "adapter-id": "EVCharger-adapter",
            "things": [
                {
                    "adapter-infra-id": "EVCharger-adapter---!---EVCharger-2",
                    "infra-id": "EVCharger-2",
                    "password": "3NsCsXkjyCRoEBksfI6LBqpTWfaynWQ/MOReG5BdF1k=",
                    "agent-id": "63a190cb-15b4-4b50-b27d-4ec5d8943081",
                    "adapter-id": "EVCharger-adapter",
                    "oid": "19204206-be5a-4b05-b2dc-2247db46832a",
                    "adapter-oid": "EVCharger-adapter---!---19204206-be5a-4b05-b2dc-2247db46832a"
                },
                {
                    "adapter-infra-id": "EVCharger-adapter---!---EVCharger-1",
                    "infra-id": "EVCharger-1",
                    "password": "cCQc5x3IUJcScXcarNn4JBxVbWplLZ6SyK1hXl4g/5Q=",
                    "agent-id": "63a190cb-15b4-4b50-b27d-4ec5d8943081",
                    "adapter-id": "EVCharger-adapter",
                    "oid": "06d61ad4-19f4-47b3-9b38-103ae9f6c12e",
                    "adapter-oid": "EVCharger-adapter---!---06d61ad4-19f4-47b3-9b38-103ae9f6c12e"
                }
            ],
            "subscribe-channels": [],
            "open-channels": []
        }
    ], 
...
```

REQUEST 
`PUT http://localhost:9997/agent/remote/objects/06d61ad4-19f4-47b3-9b38-103ae9f6c12e/properties/status`
BODY 
```
{
    "status": "test"
}
```

RESPONSE
```
{
    "error": false,
    "statusCode": 200,
    "statusCodeReason": "OK",
    "contentType": "[application/json; charset=UTF-8]",
    "message": [
        {
            "data": {
                "payload": {
                    "status": "test"
                },
                "echo": "set property",
                "pid": "status",
                "oid": "EVCharger-1"
            },
            "status": "success"
        }
    ]
}
```

REQUEST

I was expecting after making this GET request to have a response with the value "status": "test". But I do not. 

`GET http://localhost:9997/agent/remote/objects/06d61ad4-19f4-47b3-9b38-103ae9f6c12e/properties/status`

RESPONSE
``` 
{
    "error": false,
    "statusCode": 200,
    "statusCodeReason": "OK",
    "contentType": "[application/json; charset=UTF-8]",
    "message": [
        {
            "data": {
                "echo": "get property",
                "pid": "status",
                "oid": "EVCharger-1"
            },
            "status": "success"
        }
    ]
}
```

**Comment by MooXo** [comment]
Peter, please can you investigate it from Agent point of view?

**Comment by kostelni** [comment]
hi there,

u are using "example adapter", which has only one purpose: to do the echo response .. it is just example.. there is no implementation for adapter API in example adapter .. 

thus, adapter correctly responded with: "echo: put property" and "echo: get property" 

if u realy want to get/set properties or do anything reasonable, u have to implement your own adapter with custom behaviour specific for your IoT objects

cheers,
                  peter k

**Comment by quintanilha6** [comment]
> hi there,
> 
> u are using "example adapter", which has only one purpose: to do the echo response .. it is just example.. there is no implementation for adapter API in example adapter ..
> 
> thus, adapter correctly responded with: "echo: put property" and "echo: get property"
> 
> if u realy want to get/set properties or do anything reasonable, u have to implement your own adapter with custom behaviour specific for your IoT objects
> 
> cheers,
> peter k

Hello there,

Thank you for your feedback. Unfortunately, I misunderstood some part of the agent/adapter documentation. Although, with this answer together with some extra research, I managed to fix the mistake, fortunately ending up developing part of our adapter API. Thank you once again, you may close this issue if desired.

João Quintanilha
